# -*- coding: utf-8 -*-
"""Gráficos_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MnC8kNIiwY-tJH2v-D9NQ6CISWcX0eHZ
"""

import matplotlib.pyplot as plt


algoritmos = ['Bubble Sort', 'Timsort']

mediana_tempos = [38439.63, 4485.00]

media_tempos = [38099.30, 4611.00]

mediana_memoria = [4.00, 94.00]

media_memoria = [4.00, 155.60]

fig, axs = plt.subplots(2, 2, figsize=(14, 10))

# Gráfico 1 - Mediana do tempo
bars1 = axs[0, 0].bar(algoritmos, mediana_tempos, color=['red', 'green'])
axs[0, 0].set_title('Mediana do Tempo de Execução (ms)', fontsize=14)
axs[0, 0].set_ylabel('Tempo (ms)')
axs[0, 0].grid(axis='y', linestyle='--', alpha=0.7)
for bar in bars1:
    yval = bar.get_height()
    axs[0, 0].text(bar.get_x() + bar.get_width()/2, yval + 500, f'{yval:.2f} ms', ha='center', va='bottom', fontsize=10)

# Gráfico 2 - Média do tempo
bars2 = axs[0, 1].bar(algoritmos, media_tempos, color=['blue', 'orange'])
axs[0, 1].set_title('Média do Tempo de Execução (ms)', fontsize=14)
axs[0, 1].set_ylabel('Tempo (ms)')
axs[0, 1].grid(axis='y', linestyle='--', alpha=0.7)
for bar in bars2:
    yval = bar.get_height()
    axs[0, 1].text(bar.get_x() + bar.get_width()/2, yval + 500, f'{yval:.2f} ms', ha='center', va='bottom', fontsize=10)

# Gráfico 3 - Mediana da memória
bars3 = axs[1, 0].bar(algoritmos, mediana_memoria, color=['purple', 'gray'])
axs[1, 0].set_title('Mediana do Uso de Memória (KB)', fontsize=14)
axs[1, 0].set_ylabel('Memória (KB)')
axs[1, 0].grid(axis='y', linestyle='--', alpha=0.7)
for bar in bars3:
    yval = bar.get_height()
    axs[1, 0].text(bar.get_x() + bar.get_width()/2, yval + 5, f'{yval:.2f} KB', ha='center', va='bottom', fontsize=10)

# Gráfico 4 - Média da memória
bars4 = axs[1, 1].bar(algoritmos, media_memoria, color=['cyan', 'brown'])
axs[1, 1].set_title('Média do Uso de Memória (KB)', fontsize=14)
axs[1, 1].set_ylabel('Memória (KB)')
axs[1, 1].grid(axis='y', linestyle='--', alpha=0.7)
for bar in bars4:
    yval = bar.get_height()
    axs[1, 1].text(bar.get_x() + bar.get_width()/2, yval + 5, f'{yval:.2f} KB', ha='center', va='bottom', fontsize=10)


plt.tight_layout()
plt.show()